services:
  db:
    image: postgres
    restart: always
    ports:
      - '1212:5432'
    volumes:
      - /db/data
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U myuser -d ${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - /notic-redis/data
    command: [ "redis-server", "--requirepass", "${REDIS_PASSWORD}", "--appendonly", "yes" ]
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - '5050:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: ${PG_ADMIN_PASSWORD}

  notic-app:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/${DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}

      SPRING_DATA_REDIS_HOST: redis
      REDIS_PASSWORD: ${REDIS_PASSWORD}

      JWT_SECRET: ${JWT_SECRET}
      JWT_ISSUER: ${JWT_ISSUER}
      JWT_EXPIRE_TIME: ${JWT_EXPIRE_TIME}
      JWT_HEADER_ALG: ${JWT_HEADER_ALG}
      NIMBUS_ALG: ${NIMBUS_ALG}
      REFRESH_TOKEN_SECRET: ${REFRESH_TOKEN_SECRET}
      REFRESH_TOKEN_TTL: ${REFRESH_TOKEN_TTL}

      EMAIL_SENDER_USERNAME: ${EMAIL_SENDER_USERNAME}
      EMAIL_SENDER_PASSWORD: ${EMAIL_SENDER_PASSWORD}

      AWS_ACCESS_KEY: ${AWS_ACCESS_KEY}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_REGION: ${AWS_REGION}
      AWS_AVATAR_BUCKET_NAME: ${AWS_AVATAR_BUCKET_NAME}

      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}

    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
