services:
  db:
    image: postgres
    restart: always
    ports:
      - '1212:5432'
    volumes:
      - /db/data
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: mydatabase

  redis:
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - /notic-redis/data
    command: [ "redis-server", "--requirepass", "${REDIS_PASSWORD}", "--appendonly", "yes" ]

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - '5050:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: ${PG_ADMIN_PASSWORD}
